name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches so git describe works
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Podman
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          # No username/password needed for public images

      - name: Get the version
        id: get_version
        run: echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

      - name: Build application image
        run: ./container_build.sh build

      - name: Extract Binary for Artifact Upload
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir -p artifacts
          # Use podman cp to extract the binary directly from the image without running a container
          podman cp $(podman create pilo-app:latest):/usr/local/bin/pilo ./artifacts/pilo-linux-amd64

      - name: Upload Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: pilo-linux-amd64
          path: artifacts/pilo-linux-amd64