name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

      - name: Build application in container
        run: ./container_build.sh build

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Extract binary from container
        run: |
          CONTAINER_ID=$(docker create pilo-app:latest)
          docker cp ${CONTAINER_ID}:/usr/local/bin/pilo ./artifacts/pilo-linux-amd64
          docker rm ${CONTAINER_ID}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pilo-linux-amd64
          path: artifacts/pilo-linux-amd64