name: Build Application

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        go-version: ['1.22']
        platform:
          - linux/amd64
          - linux/arm64
          - linux/riscv64
          - darwin/amd64
          - darwin/arm64
          - windows/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run xgo
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: ${{ matrix.go-version }}
          dest: bin
          prefix: pilo
          targets: ${{ matrix.platform }}
          v: true
          x: true
          race: true
          ldflags: -s -w

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pilo-${{ matrix.platform }}
          path: bin/pilo-*